apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-service
  template:
    metadata:
      labels:
        app: iam-service
    spec:
      containers:
      - name: iam-service
        image: app.io/your-project/iam-service:latest
        ports:
        - containerPort: 80
